export enum TickerColumnMapper{
    Ticker ='A',
    Price = 'C',
    ChangePercent = 'D',
    WeeklyPerformance = 'E',
    MonthlyPerformance = 'F',
    ThreeMonthPerformance = 'G',
    SixMonthPerformance = 'H',
    YearlyPerformance = 'I',
    Industry = 'J',
    RelativeVolume = 'K',
    Volatility = 'L',
    VolatilityWeek = 'M',
    VolatilityMonth = 'N',
    Volume = 'O',
    AverageVolume = 'P',
    SharesFloat = 'Q',
    MarketCap = 'R',
    UpcomingEarnings = 'S',
    FiveTwoWeekHigh = 'T',
    FiveTwoWeekLow = 'U',
    SimpleMovingAverageFiveZero = 'V',
}